version: "3"

services:
  new_week:
    build:
      context: new_week/
    restart: always
    env_file: .env
  dashcontrol:
    build:
      context: dashcontrol/
    restart: always
    env_file: .env
    ports:
      - "8000:8000"